---
title: "Reproducible Reports"
subtitle: "using R Markdown"
author: "Pieter Moors"
date: "2017/02/09"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: center, middle

# Why?

---

# Has this ever bothered you? 

- Copypasting statistics output into the draft of a paper

--

- Making sure you did not make any rounding errors

--

- Having to update a figure after remarks by your supervisor/reviewer

--

- What were the parameter settings of my experiment again? 

---
class: center, middle

#Enter R Markdown

---

# What are the advantages?

- You can **embed** R code in your document 

- You write **dynamic** documents 

- You **export** it to HTML, PDF, or Word 

- It is really **easy** (for most stuff)

---

# What is R Markdown? 

Markdown is a formatting language. You can write plain text. It is really use to use the features. 

R Markdown is a nice extension. Some features were added, such as code embedding. 

---

# Is it really that good? 

Yes. Unless you are addicted to WYSIWYG ("What you see is what you get").

---

# When should I use it? 

Every analysis you do from now on.

Every paper you write from now on (**advanced**).

---

class: inverse, middle, center

# Let's jump in 
